<?php

return [
    [
        'country_iso_code' => 'AX',
        'country_call_prefix' => '0',
        'country_name' => 'Åland Islands',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'AL',
        'country_call_prefix' => '355',
        'country_name' => 'Albania',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'AD',
        'country_call_prefix' => '376',
        'country_name' => 'Andorra',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'BY',
        'country_call_prefix' => '0',
        'country_name' => 'Belarus',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'BA',
        'country_call_prefix' => '387',
        'country_name' => 'Bosnia and Herzegovina',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'FO',
        'country_call_prefix' => '298',
        'country_name' => 'Faroe Islands',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'GI',
        'country_call_prefix' => '350',
        'country_name' => 'Gibraltar',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'GL',
        'country_call_prefix' => '299',
        'country_name' => 'Greenland',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'GG',
        'country_call_prefix' => '0',
        'country_name' => 'Guernsey',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'IS',
        'country_call_prefix' => '354',
        'country_name' => 'Iceland',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'JE',
        'country_call_prefix' => '0',
        'country_name' => 'Jersey',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'LI',
        'country_call_prefix' => '423',
        'country_name' => 'Liechtenstein',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'MK',
        'country_call_prefix' => '389',
        'country_name' => 'Macedonia',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'IM',
        'country_call_prefix' => '0',
        'country_name' => 'Man Island',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'MD',
        'country_call_prefix' => '373',
        'country_name' => 'Moldova',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'MC',
        'country_call_prefix' => '377',
        'country_name' => 'Monaco',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'ME',
        'country_call_prefix' => '382',
        'country_name' => 'Montenegro',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'NO',
        'country_call_prefix' => '47',
        'country_name' => 'Norway',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'RU',
        'country_call_prefix' => '7',
        'country_name' => 'Russian Federation',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'SM',
        'country_call_prefix' => '378',
        'country_name' => 'San Marino',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'RS',
        'country_call_prefix' => '381',
        'country_name' => 'Serbia',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'SJ',
        'country_call_prefix' => '0',
        'country_name' => 'Svalbard and Jan Mayen',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'CH',
        'country_call_prefix' => '41',
        'country_name' => 'Switzerland',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'TR',
        'country_call_prefix' => '90',
        'country_name' => 'Turkey',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'UA',
        'country_call_prefix' => '380',
        'country_name' => 'Ukraine',
        'zone_name' => 'Europe (non-EU)',
    ],
    [
        'country_iso_code' => 'VA',
        'country_call_prefix' => '379',
        'country_name' => 'Vatican City State',
        'zone_name' => 'Europe (non-EU)',
    ],
];
