<?php

$list = [
    [
        0 => [
            'country_iso_code' => 'DZ',
            'country_call_prefix' => '213',
            'country_name' => 'Algeria',
            'zone_name' => 'Africa',
        ],
        1 => [
            'country_iso_code' => 'AO',
            'country_call_prefix' => '244',
            'country_name' => 'Angola',
            'zone_name' => 'Africa',
        ],
        2 => [
            'country_iso_code' => 'BJ',
            'country_call_prefix' => '229',
            'country_name' => 'Benin',
            'zone_name' => 'Africa',
        ],
        3 => [
            'country_iso_code' => 'BW',
            'country_call_prefix' => '267',
            'country_name' => 'Botswana',
            'zone_name' => 'Africa',
        ],
        4 => [
            'country_iso_code' => 'BF',
            'country_call_prefix' => '226',
            'country_name' => 'Burkina Faso',
            'zone_name' => 'Africa',
        ],
        5 => [
            'country_iso_code' => 'BI',
            'country_call_prefix' => '257',
            'country_name' => 'Burundi',
            'zone_name' => 'Africa',
        ],
        6 => [
            'country_iso_code' => 'CM',
            'country_call_prefix' => '237',
            'country_name' => 'Cameroon',
            'zone_name' => 'Africa',
        ],
        7 => [
            'country_iso_code' => 'CV',
            'country_call_prefix' => '238',
            'country_name' => 'Cape Verde',
            'zone_name' => 'Africa',
        ],
        8 => [
            'country_iso_code' => 'CF',
            'country_call_prefix' => '236',
            'country_name' => 'Central African Republic',
            'zone_name' => 'Africa',
        ],
        9 => [
            'country_iso_code' => 'TD',
            'country_call_prefix' => '235',
            'country_name' => 'Chad',
            'zone_name' => 'Africa',
        ],
        10 => [
            'country_iso_code' => 'KM',
            'country_call_prefix' => '269',
            'country_name' => 'Comoros',
            'zone_name' => 'Africa',
        ],
        11 => [
            'country_iso_code' => 'CD',
            'country_call_prefix' => '242',
            'country_name' => 'Congo, Dem. Republic',
            'zone_name' => 'Africa',
        ],
        12 => [
            'country_iso_code' => 'CG',
            'country_call_prefix' => '243',
            'country_name' => 'Congo, Republic',
            'zone_name' => 'Africa',
        ],
        13 => [
            'country_iso_code' => 'DJ',
            'country_call_prefix' => '253',
            'country_name' => 'Djibouti',
            'zone_name' => 'Africa',
        ],
        14 => [
            'country_iso_code' => 'EG',
            'country_call_prefix' => '20',
            'country_name' => 'Egypt',
            'zone_name' => 'Africa',
        ],
        15 => [
            'country_iso_code' => 'GQ',
            'country_call_prefix' => '240',
            'country_name' => 'Equatorial Guinea',
            'zone_name' => 'Africa',
        ],
        16 => [
            'country_iso_code' => 'ER',
            'country_call_prefix' => '291',
            'country_name' => 'Eritrea',
            'zone_name' => 'Africa',
        ],
        17 => [
            'country_iso_code' => 'ET',
            'country_call_prefix' => '251',
            'country_name' => 'Ethiopia',
            'zone_name' => 'Africa',
        ],
        18 => [
            'country_iso_code' => 'GA',
            'country_call_prefix' => '241',
            'country_name' => 'Gabon',
            'zone_name' => 'Africa',
        ],
        19 => [
            'country_iso_code' => 'GM',
            'country_call_prefix' => '220',
            'country_name' => 'Gambia',
            'zone_name' => 'Africa',
        ],
        20 => [
            'country_iso_code' => 'GH',
            'country_call_prefix' => '233',
            'country_name' => 'Ghana',
            'zone_name' => 'Africa',
        ],
        21 => [
            'country_iso_code' => 'GN',
            'country_call_prefix' => '224',
            'country_name' => 'Guinea',
            'zone_name' => 'Africa',
        ],
        22 => [
            'country_iso_code' => 'GW',
            'country_call_prefix' => '245',
            'country_name' => 'Guinea-Bissau',
            'zone_name' => 'Africa',
        ],
        23 => [
            'country_iso_code' => 'CI',
            'country_call_prefix' => '225',
            'country_name' => 'Ivory Coast',
            'zone_name' => 'Africa',
        ],
        24 => [
            'country_iso_code' => 'KE',
            'country_call_prefix' => '254',
            'country_name' => 'Kenya',
            'zone_name' => 'Africa',
        ],
        25 => [
            'country_iso_code' => 'LS',
            'country_call_prefix' => '266',
            'country_name' => 'Lesotho',
            'zone_name' => 'Africa',
        ],
        26 => [
            'country_iso_code' => 'LR',
            'country_call_prefix' => '231',
            'country_name' => 'Liberia',
            'zone_name' => 'Africa',
        ],
        27 => [
            'country_iso_code' => 'LY',
            'country_call_prefix' => '218',
            'country_name' => 'Libya',
            'zone_name' => 'Africa',
        ],
        28 => [
            'country_iso_code' => 'MG',
            'country_call_prefix' => '261',
            'country_name' => 'Madagascar',
            'zone_name' => 'Africa',
        ],
        29 => [
            'country_iso_code' => 'MW',
            'country_call_prefix' => '265',
            'country_name' => 'Malawi',
            'zone_name' => 'Africa',
        ],
        30 => [
            'country_iso_code' => 'ML',
            'country_call_prefix' => '223',
            'country_name' => 'Mali',
            'zone_name' => 'Africa',
        ],
        31 => [
            'country_iso_code' => 'MR',
            'country_call_prefix' => '222',
            'country_name' => 'Mauritania',
            'zone_name' => 'Africa',
        ],
        32 => [
            'country_iso_code' => 'MU',
            'country_call_prefix' => '230',
            'country_name' => 'Mauritius',
            'zone_name' => 'Africa',
        ],
        33 => [
            'country_iso_code' => 'YT',
            'country_call_prefix' => '262',
            'country_name' => 'Mayotte',
            'zone_name' => 'Africa',
        ],
        34 => [
            'country_iso_code' => 'MA',
            'country_call_prefix' => '212',
            'country_name' => 'Morocco',
            'zone_name' => 'Africa',
        ],
        35 => [
            'country_iso_code' => 'MZ',
            'country_call_prefix' => '258',
            'country_name' => 'Mozambique',
            'zone_name' => 'Africa',
        ],
        36 => [
            'country_iso_code' => 'NA',
            'country_call_prefix' => '264',
            'country_name' => 'Namibia',
            'zone_name' => 'Africa',
        ],
        37 => [
            'country_iso_code' => 'NE',
            'country_call_prefix' => '227',
            'country_name' => 'Niger',
            'zone_name' => 'Africa',
        ],
        38 => [
            'country_iso_code' => 'NG',
            'country_call_prefix' => '234',
            'country_name' => 'Nigeria',
            'zone_name' => 'Africa',
        ],
        39 => [
            'country_iso_code' => 'RE',
            'country_call_prefix' => '262',
            'country_name' => 'Reunion Island',
            'zone_name' => 'Africa',
        ],
        40 => [
            'country_iso_code' => 'RW',
            'country_call_prefix' => '250',
            'country_name' => 'Rwanda',
            'zone_name' => 'Africa',
        ],
        41 => [
            'country_iso_code' => 'ST',
            'country_call_prefix' => '239',
            'country_name' => 'São Tomé and Príncipe',
            'zone_name' => 'Africa',
        ],
        42 => [
            'country_iso_code' => 'SN',
            'country_call_prefix' => '221',
            'country_name' => 'Senegal',
            'zone_name' => 'Africa',
        ],
        43 => [
            'country_iso_code' => 'SC',
            'country_call_prefix' => '248',
            'country_name' => 'Seychelles',
            'zone_name' => 'Africa',
        ],
        44 => [
            'country_iso_code' => 'SL',
            'country_call_prefix' => '232',
            'country_name' => 'Sierra Leone',
            'zone_name' => 'Africa',
        ],
        45 => [
            'country_iso_code' => 'SO',
            'country_call_prefix' => '252',
            'country_name' => 'Somalia',
            'zone_name' => 'Africa',
        ],
        46 => [
            'country_iso_code' => 'ZA',
            'country_call_prefix' => '27',
            'country_name' => 'South Africa',
            'zone_name' => 'Africa',
        ],
        47 => [
            'country_iso_code' => 'SD',
            'country_call_prefix' => '249',
            'country_name' => 'Sudan',
            'zone_name' => 'Africa',
        ],
        48 => [
            'country_iso_code' => 'SZ',
            'country_call_prefix' => '268',
            'country_name' => 'Swaziland',
            'zone_name' => 'Africa',
        ],
        49 => [
            'country_iso_code' => 'TZ',
            'country_call_prefix' => '255',
            'country_name' => 'Tanzania',
            'zone_name' => 'Africa',
        ],
        50 => [
            'country_iso_code' => 'TG',
            'country_call_prefix' => '228',
            'country_name' => 'Togo',
            'zone_name' => 'Africa',
        ],
        51 => [
            'country_iso_code' => 'TN',
            'country_call_prefix' => '216',
            'country_name' => 'Tunisia',
            'zone_name' => 'Africa',
        ],
        52 => [
            'country_iso_code' => 'UG',
            'country_call_prefix' => '256',
            'country_name' => 'Uganda',
            'zone_name' => 'Africa',
        ],
        53 => [
            'country_iso_code' => 'EH',
            'country_call_prefix' => '0',
            'country_name' => 'Western Sahara',
            'zone_name' => 'Africa',
        ],
        54 => [
            'country_iso_code' => 'ZM',
            'country_call_prefix' => '260',
            'country_name' => 'Zambia',
            'zone_name' => 'Africa',
        ],
        55 => [
            'country_iso_code' => 'ZW',
            'country_call_prefix' => '263',
            'country_name' => 'Zimbabwe',
            'zone_name' => 'Africa',
        ],
    ],
];
