<?php

$list = [
    [
        0 => [
            'country_iso_code' => 'AF',
            'country_call_prefix' => '93',
            'country_name' => 'Afghanistan',
            'zone_name' => 'Asia',
        ],
        1 => [
            'country_iso_code' => 'AM',
            'country_call_prefix' => '374',
            'country_name' => 'Armenia',
            'zone_name' => 'Asia',
        ],
        2 => [
            'country_iso_code' => 'AZ',
            'country_call_prefix' => '994',
            'country_name' => 'Azerbaijan',
            'zone_name' => 'Asia',
        ],
        3 => [
            'country_iso_code' => 'BH',
            'country_call_prefix' => '973',
            'country_name' => 'Bahrain',
            'zone_name' => 'Asia',
        ],
        4 => [
            'country_iso_code' => 'BD',
            'country_call_prefix' => '880',
            'country_name' => 'Bangladesh',
            'zone_name' => 'Asia',
        ],
        5 => [
            'country_iso_code' => 'BT',
            'country_call_prefix' => '975',
            'country_name' => 'Bhutan',
            'zone_name' => 'Asia',
        ],
        6 => [
            'country_iso_code' => 'BN',
            'country_call_prefix' => '673',
            'country_name' => 'Brunei',
            'zone_name' => 'Asia',
        ],
        7 => [
            'country_iso_code' => 'MM',
            'country_call_prefix' => '95',
            'country_name' => 'Burma (Myanmar)',
            'zone_name' => 'Asia',
        ],
        8 => [
            'country_iso_code' => 'KH',
            'country_call_prefix' => '855',
            'country_name' => 'Cambodia',
            'zone_name' => 'Asia',
        ],
        9 => [
            'country_iso_code' => 'CN',
            'country_call_prefix' => '86',
            'country_name' => 'China',
            'zone_name' => 'Asia',
        ],
        10 => [
            'country_iso_code' => 'CX',
            'country_call_prefix' => '0',
            'country_name' => 'Christmas Island',
            'zone_name' => 'Asia',
        ],
        11 => [
            'country_iso_code' => 'CC',
            'country_call_prefix' => '0',
            'country_name' => 'Cocos (Keeling) Islands',
            'zone_name' => 'Asia',
        ],
        12 => [
            'country_iso_code' => 'TL',
            'country_call_prefix' => '670',
            'country_name' => 'East Timor',
            'zone_name' => 'Asia',
        ],
        13 => [
            'country_iso_code' => 'GE',
            'country_call_prefix' => '995',
            'country_name' => 'Georgia',
            'zone_name' => 'Asia',
        ],
        14 => [
            'country_iso_code' => 'HK',
            'country_call_prefix' => '852',
            'country_name' => 'HongKong',
            'zone_name' => 'Asia',
        ],
        15 => [
            'country_iso_code' => 'IN',
            'country_call_prefix' => '91',
            'country_name' => 'India',
            'zone_name' => 'Asia',
        ],
        16 => [
            'country_iso_code' => 'ID',
            'country_call_prefix' => '62',
            'country_name' => 'Indonesia',
            'zone_name' => 'Asia',
        ],
        17 => [
            'country_iso_code' => 'IR',
            'country_call_prefix' => '98',
            'country_name' => 'Iran',
            'zone_name' => 'Asia',
        ],
        18 => [
            'country_iso_code' => 'IQ',
            'country_call_prefix' => '964',
            'country_name' => 'Iraq',
            'zone_name' => 'Asia',
        ],
        19 => [
            'country_iso_code' => 'IL',
            'country_call_prefix' => '972',
            'country_name' => 'Israel',
            'zone_name' => 'Asia',
        ],
        20 => [
            'country_iso_code' => 'JP',
            'country_call_prefix' => '81',
            'country_name' => 'Japan',
            'zone_name' => 'Asia',
        ],
        21 => [
            'country_iso_code' => 'JO',
            'country_call_prefix' => '962',
            'country_name' => 'Jordan',
            'zone_name' => 'Asia',
        ],
        22 => [
            'country_iso_code' => 'KZ',
            'country_call_prefix' => '7',
            'country_name' => 'Kazakhstan',
            'zone_name' => 'Asia',
        ],
        23 => [
            'country_iso_code' => 'KP',
            'country_call_prefix' => '850',
            'country_name' => 'Korea, Dem. Republic of',
            'zone_name' => 'Asia',
        ],
        24 => [
            'country_iso_code' => 'KW',
            'country_call_prefix' => '965',
            'country_name' => 'Kuwait',
            'zone_name' => 'Asia',
        ],
        25 => [
            'country_iso_code' => 'KG',
            'country_call_prefix' => '996',
            'country_name' => 'Kyrgyzstan',
            'zone_name' => 'Asia',
        ],
        26 => [
            'country_iso_code' => 'LA',
            'country_call_prefix' => '856',
            'country_name' => 'Laos',
            'zone_name' => 'Asia',
        ],
        27 => [
            'country_iso_code' => 'LB',
            'country_call_prefix' => '961',
            'country_name' => 'Lebanon',
            'zone_name' => 'Asia',
        ],
        28 => [
            'country_iso_code' => 'MO',
            'country_call_prefix' => '853',
            'country_name' => 'Macau',
            'zone_name' => 'Asia',
        ],
        29 => [
            'country_iso_code' => 'MY',
            'country_call_prefix' => '60',
            'country_name' => 'Malaysia',
            'zone_name' => 'Asia',
        ],
        30 => [
            'country_iso_code' => 'MV',
            'country_call_prefix' => '960',
            'country_name' => 'Maldives',
            'zone_name' => 'Asia',
        ],
        31 => [
            'country_iso_code' => 'MN',
            'country_call_prefix' => '976',
            'country_name' => 'Mongolia',
            'zone_name' => 'Asia',
        ],
        32 => [
            'country_iso_code' => 'NP',
            'country_call_prefix' => '977',
            'country_name' => 'Nepal',
            'zone_name' => 'Asia',
        ],
        33 => [
            'country_iso_code' => 'OM',
            'country_call_prefix' => '968',
            'country_name' => 'Oman',
            'zone_name' => 'Asia',
        ],
        34 => [
            'country_iso_code' => 'PK',
            'country_call_prefix' => '92',
            'country_name' => 'Pakistan',
            'zone_name' => 'Asia',
        ],
        35 => [
            'country_iso_code' => 'PS',
            'country_call_prefix' => '0',
            'country_name' => 'Palestinian Territories',
            'zone_name' => 'Asia',
        ],
        36 => [
            'country_iso_code' => 'PH',
            'country_call_prefix' => '63',
            'country_name' => 'Philippines',
            'zone_name' => 'Asia',
        ],
        37 => [
            'country_iso_code' => 'QA',
            'country_call_prefix' => '974',
            'country_name' => 'Qatar',
            'zone_name' => 'Asia',
        ],
        38 => [
            'country_iso_code' => 'SA',
            'country_call_prefix' => '966',
            'country_name' => 'Saudi Arabia',
            'zone_name' => 'Asia',
        ],
        39 => [
            'country_iso_code' => 'SG',
            'country_call_prefix' => '65',
            'country_name' => 'Singapore',
            'zone_name' => 'Asia',
        ],
        40 => [
            'country_iso_code' => 'KR',
            'country_call_prefix' => '82',
            'country_name' => 'South Korea',
            'zone_name' => 'Asia',
        ],
        41 => [
            'country_iso_code' => 'LK',
            'country_call_prefix' => '94',
            'country_name' => 'Sri Lanka',
            'zone_name' => 'Asia',
        ],
        42 => [
            'country_iso_code' => 'SY',
            'country_call_prefix' => '963',
            'country_name' => 'Syria',
            'zone_name' => 'Asia',
        ],
        43 => [
            'country_iso_code' => 'TW',
            'country_call_prefix' => '886',
            'country_name' => 'Taiwan',
            'zone_name' => 'Asia',
        ],
        44 => [
            'country_iso_code' => 'TJ',
            'country_call_prefix' => '992',
            'country_name' => 'Tajikistan',
            'zone_name' => 'Asia',
        ],
        45 => [
            'country_iso_code' => 'TH',
            'country_call_prefix' => '66',
            'country_name' => 'Thailand',
            'zone_name' => 'Asia',
        ],
        46 => [
            'country_iso_code' => 'TM',
            'country_call_prefix' => '993',
            'country_name' => 'Turkmenistan',
            'zone_name' => 'Asia',
        ],
        47 => [
            'country_iso_code' => 'AE',
            'country_call_prefix' => '971',
            'country_name' => 'United Arab Emirates',
            'zone_name' => 'Asia',
        ],
        48 => [
            'country_iso_code' => 'UZ',
            'country_call_prefix' => '998',
            'country_name' => 'Uzbekistan',
            'zone_name' => 'Asia',
        ],
        49 => [
            'country_iso_code' => 'VN',
            'country_call_prefix' => '84',
            'country_name' => 'Vietnam',
            'zone_name' => 'Asia',
        ],
        50 => [
            'country_iso_code' => 'YE',
            'country_call_prefix' => '967',
            'country_name' => 'Yemen',
            'zone_name' => 'Asia',
        ],
    ],
];
