<?php

$list = [
    [
        [
            'country_iso_code' => 'AI',
            'country_call_prefix' => '0',
            'country_name' => 'Anguilla',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'AW',
            'country_call_prefix' => '297',
            'country_name' => 'Aruba',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'BZ',
            'country_call_prefix' => '501',
            'country_name' => 'Belize',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'KY',
            'country_call_prefix' => '0',
            'country_name' => 'Cayman Islands',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'CR',
            'country_call_prefix' => '506',
            'country_name' => 'Costa Rica',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'CU',
            'country_call_prefix' => '53',
            'country_name' => 'Cuba',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'DM',
            'country_call_prefix' => '0',
            'country_name' => 'Dominica',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'DO',
            'country_call_prefix' => '0',
            'country_name' => 'Dominican Republic',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'SV',
            'country_call_prefix' => '503',
            'country_name' => 'El Salvador',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'FK',
            'country_call_prefix' => '0',
            'country_name' => 'Falkland Islands',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'GD',
            'country_call_prefix' => '0',
            'country_name' => 'Grenada',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'GP',
            'country_call_prefix' => '590',
            'country_name' => 'Guadeloupe',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'GT',
            'country_call_prefix' => '502',
            'country_name' => 'Guatemala',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'HT',
            'country_call_prefix' => '509',
            'country_name' => 'Haiti',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'HN',
            'country_call_prefix' => '504',
            'country_name' => 'Honduras',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'JM',
            'country_call_prefix' => '0',
            'country_name' => 'Jamaica',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'MQ',
            'country_call_prefix' => '596',
            'country_name' => 'Martinique',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'MS',
            'country_call_prefix' => '0',
            'country_name' => 'Montserrat',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'AN',
            'country_call_prefix' => '599',
            'country_name' => 'Netherlands Antilles',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'NI',
            'country_call_prefix' => '505',
            'country_name' => 'Nicaragua',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'PA',
            'country_call_prefix' => '507',
            'country_name' => 'Panama',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'PR',
            'country_call_prefix' => '0',
            'country_name' => 'Puerto Rico',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'BL',
            'country_call_prefix' => '0',
            'country_name' => 'Saint Barthelemy',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'KN',
            'country_call_prefix' => '0',
            'country_name' => 'Saint Kitts and Nevis',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'LC',
            'country_call_prefix' => '0',
            'country_name' => 'Saint Lucia',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'MF',
            'country_call_prefix' => '0',
            'country_name' => 'Saint Martin',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'PM',
            'country_call_prefix' => '508',
            'country_name' => 'Saint Pierre and Miquelon',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'VC',
            'country_call_prefix' => '0',
            'country_name' => 'Saint Vincent and the Grenadines',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'GS',
            'country_call_prefix' => '0',
            'country_name' => 'South Georgia and the South Sandwich Islands',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'SR',
            'country_call_prefix' => '597',
            'country_name' => 'Suriname',
            'zone_name' => 'Central America/Antilla',
        ],
        [
            'country_iso_code' => 'TC',
            'country_call_prefix' => '0',
            'country_name' => 'Turks and Caicos Islands',
            'zone_name' => 'Central America/Antilla',
        ],
    ],
];
