<?php

$list = [
    [
        0 => [
            'country_iso_code' => 'AT',
            'country_call_prefix' => '43',
            'country_name' => 'Austria',
            'zone_name' => 'Europe',
        ],
        1 => [
            'country_iso_code' => 'BE',
            'country_call_prefix' => '32',
            'country_name' => 'Belgium',
            'zone_name' => 'Europe',
        ],
        2 => [
            'country_iso_code' => 'BG',
            'country_call_prefix' => '359',
            'country_name' => 'Bulgaria',
            'zone_name' => 'Europe',
        ],
        3 => [
            'country_iso_code' => 'HR',
            'country_call_prefix' => '385',
            'country_name' => 'Croatia',
            'zone_name' => 'Europe',
        ],
        4 => [
            'country_iso_code' => 'CY',
            'country_call_prefix' => '357',
            'country_name' => 'Cyprus',
            'zone_name' => 'Europe',
        ],
        5 => [
            'country_iso_code' => 'CZ',
            'country_call_prefix' => '420',
            'country_name' => 'Czech Republic',
            'zone_name' => 'Europe',
        ],
        6 => [
            'country_iso_code' => 'DK',
            'country_call_prefix' => '45',
            'country_name' => 'Denmark',
            'zone_name' => 'Europe',
        ],
        7 => [
            'country_iso_code' => 'EE',
            'country_call_prefix' => '372',
            'country_name' => 'Estonia',
            'zone_name' => 'Europe',
        ],
        8 => [
            'country_iso_code' => 'FI',
            'country_call_prefix' => '358',
            'country_name' => 'Finland',
            'zone_name' => 'Europe',
        ],
        9 => [
            'country_iso_code' => 'FR',
            'country_call_prefix' => '33',
            'country_name' => 'France',
            'zone_name' => 'Europe',
        ],
        10 => [
            'country_iso_code' => 'DE',
            'country_call_prefix' => '49',
            'country_name' => 'Germany',
            'zone_name' => 'Europe',
        ],
        11 => [
            'country_iso_code' => 'GR',
            'country_call_prefix' => '30',
            'country_name' => 'Greece',
            'zone_name' => 'Europe',
        ],
        12 => [
            'country_iso_code' => 'HU',
            'country_call_prefix' => '36',
            'country_name' => 'Hungary',
            'zone_name' => 'Europe',
        ],
        13 => [
            'country_iso_code' => 'IE',
            'country_call_prefix' => '353',
            'country_name' => 'Ireland',
            'zone_name' => 'Europe',
        ],
        14 => [
            'country_iso_code' => 'IT',
            'country_call_prefix' => '39',
            'country_name' => 'Italy',
            'zone_name' => 'Europe',
        ],
        15 => [
            'country_iso_code' => 'LV',
            'country_call_prefix' => '371',
            'country_name' => 'Latvia',
            'zone_name' => 'Europe',
        ],
        16 => [
            'country_iso_code' => 'LT',
            'country_call_prefix' => '370',
            'country_name' => 'Lithuania',
            'zone_name' => 'Europe',
        ],
        17 => [
            'country_iso_code' => 'LU',
            'country_call_prefix' => '352',
            'country_name' => 'Luxemburg',
            'zone_name' => 'Europe',
        ],
        18 => [
            'country_iso_code' => 'MT',
            'country_call_prefix' => '356',
            'country_name' => 'Malta',
            'zone_name' => 'Europe',
        ],
        19 => [
            'country_iso_code' => 'NL',
            'country_call_prefix' => '31',
            'country_name' => 'Netherlands',
            'zone_name' => 'Europe',
        ],
        20 => [
            'country_iso_code' => 'PL',
            'country_call_prefix' => '48',
            'country_name' => 'Poland',
            'zone_name' => 'Europe',
        ],
        21 => [
            'country_iso_code' => 'PT',
            'country_call_prefix' => '351',
            'country_name' => 'Portugal',
            'zone_name' => 'Europe',
        ],
        22 => [
            'country_iso_code' => 'RO',
            'country_call_prefix' => '40',
            'country_name' => 'Romania',
            'zone_name' => 'Europe',
        ],
        23 => [
            'country_iso_code' => 'SK',
            'country_call_prefix' => '421',
            'country_name' => 'Slovakia',
            'zone_name' => 'Europe',
        ],
        24 => [
            'country_iso_code' => 'SI',
            'country_call_prefix' => '386',
            'country_name' => 'Slovenia',
            'zone_name' => 'Europe',
        ],
        25 => [
            'country_iso_code' => 'ES',
            'country_call_prefix' => '34',
            'country_name' => 'Spain',
            'zone_name' => 'Europe',
        ],
        26 => [
            'country_iso_code' => 'SE',
            'country_call_prefix' => '46',
            'country_name' => 'Sweden',
            'zone_name' => 'Europe',
        ],
        27 => [
            'country_iso_code' => 'GB',
            'country_call_prefix' => '44',
            'country_name' => 'United Kingdom',
            'zone_name' => 'Europe',
        ],
    ],
];