<?php

$list = [
    [
        0 => [
            'country_iso_code' => 'AQ',
            'country_call_prefix' => '0',
            'country_name' => 'Antarctica',
            'zone_name' => 'Oceania',
        ],
        1 => [
            'country_iso_code' => 'AU',
            'country_call_prefix' => '61',
            'country_name' => 'Australia',
            'zone_name' => 'Oceania',
        ],
        2 => [
            'country_iso_code' => 'BV',
            'country_call_prefix' => '0',
            'country_name' => 'Bouvet Island',
            'zone_name' => 'Oceania',
        ],
        3 => [
            'country_iso_code' => 'IO',
            'country_call_prefix' => '0',
            'country_name' => 'British Indian Ocean Territory',
            'zone_name' => 'Oceania',
        ],
        4 => [
            'country_iso_code' => 'CK',
            'country_call_prefix' => '682',
            'country_name' => 'Cook Islands',
            'zone_name' => 'Oceania',
        ],
        5 => [
            'country_iso_code' => 'FJ',
            'country_call_prefix' => '679',
            'country_name' => 'Fiji',
            'zone_name' => 'Oceania',
        ],
        6 => [
            'country_iso_code' => 'PF',
            'country_call_prefix' => '689',
            'country_name' => 'French Polynesia',
            'zone_name' => 'Oceania',
        ],
        7 => [
            'country_iso_code' => 'TF',
            'country_call_prefix' => '0',
            'country_name' => 'French Southern Territories',
            'zone_name' => 'Oceania',
        ],
        8 => [
            'country_iso_code' => 'GU',
            'country_call_prefix' => '0',
            'country_name' => 'Guam',
            'zone_name' => 'Oceania',
        ],
        9 => [
            'country_iso_code' => 'HM',
            'country_call_prefix' => '0',
            'country_name' => 'Heard Island and McDonald Islands',
            'zone_name' => 'Oceania',
        ],
        10 => [
            'country_iso_code' => 'KI',
            'country_call_prefix' => '686',
            'country_name' => 'Kiribati',
            'zone_name' => 'Oceania',
        ],
        11 => [
            'country_iso_code' => 'MH',
            'country_call_prefix' => '692',
            'country_name' => 'Marshall Islands',
            'zone_name' => 'Oceania',
        ],
        12 => [
            'country_iso_code' => 'FM',
            'country_call_prefix' => '691',
            'country_name' => 'Micronesia',
            'zone_name' => 'Oceania',
        ],
        13 => [
            'country_iso_code' => 'NR',
            'country_call_prefix' => '674',
            'country_name' => 'Nauru',
            'zone_name' => 'Oceania',
        ],
        14 => [
            'country_iso_code' => 'NC',
            'country_call_prefix' => '687',
            'country_name' => 'New Caledonia',
            'zone_name' => 'Oceania',
        ],
        15 => [
            'country_iso_code' => 'NZ',
            'country_call_prefix' => '64',
            'country_name' => 'New Zealand',
            'zone_name' => 'Oceania',
        ],
        16 => [
            'country_iso_code' => 'NU',
            'country_call_prefix' => '683',
            'country_name' => 'Niue',
            'zone_name' => 'Oceania',
        ],
        17 => [
            'country_iso_code' => 'NF',
            'country_call_prefix' => '0',
            'country_name' => 'Norfolk Island',
            'zone_name' => 'Oceania',
        ],
        18 => [
            'country_iso_code' => 'MP',
            'country_call_prefix' => '0',
            'country_name' => 'Northern Mariana Islands',
            'zone_name' => 'Oceania',
        ],
        19 => [
            'country_iso_code' => 'PW',
            'country_call_prefix' => '680',
            'country_name' => 'Palau',
            'zone_name' => 'Oceania',
        ],
        20 => [
            'country_iso_code' => 'PG',
            'country_call_prefix' => '675',
            'country_name' => 'Papua New Guinea',
            'zone_name' => 'Oceania',
        ],
        21 => [
            'country_iso_code' => 'PN',
            'country_call_prefix' => '0',
            'country_name' => 'Pitcairn',
            'zone_name' => 'Oceania',
        ],
        22 => [
            'country_iso_code' => 'WS',
            'country_call_prefix' => '685',
            'country_name' => 'Samoa',
            'zone_name' => 'Oceania',
        ],
        23 => [
            'country_iso_code' => 'SB',
            'country_call_prefix' => '677',
            'country_name' => 'Solomon Islands',
            'zone_name' => 'Oceania',
        ],
        24 => [
            'country_iso_code' => 'TK',
            'country_call_prefix' => '690',
            'country_name' => 'Tokelau',
            'zone_name' => 'Oceania',
        ],
        25 => [
            'country_iso_code' => 'TO',
            'country_call_prefix' => '676',
            'country_name' => 'Tonga',
            'zone_name' => 'Oceania',
        ],
        26 => [
            'country_iso_code' => 'TV',
            'country_call_prefix' => '688',
            'country_name' => 'Tuvalu',
            'zone_name' => 'Oceania',
        ],
        27 => [
            'country_iso_code' => 'VU',
            'country_call_prefix' => '678',
            'country_name' => 'Vanuatu',
            'zone_name' => 'Oceania',
        ],
        28 => [
            'country_iso_code' => 'WF',
            'country_call_prefix' => '681',
            'country_name' => 'Wallis and Futuna',
            'zone_name' => 'Oceania',
        ],
    ],
];
